"""locust project CRUD operations performance test"""
from locust import HttpUser, task, between
import random
from app.core.config import settings


class ProjectUser(HttpUser):
    """project CRUD operations performance"""
    wait_time = between(1, 3)
    host = f"http://{'localhost' if settings.HOST == '0.0.0.0' else settings.HOST}:{settings.PORT}"

    def on_start(self):
        """setup: register, login and create initial project"""
        self.token = None
        self.project_ids = []
        self.email = f"projecttest_{random.randint(100000, 999999)}@example.com"
        self.password = "TestPassword123!"
        self._register_and_login()
        if self.token:
            self._create_initial_project()

    def _register_and_login(self):
        """register user if needed and login"""
        register_data = {
            "email": self.email,
            "password": self.password,
            "first_name": "Project",
            "last_name": "Test"
        }
        register_response = self.client.post("/api/v1/auth/register", json=register_data)
        # only try login if registration succeeded (201) or user already exists (400)
        if register_response.status_code == 201 or (
            register_response.status_code == 400 and 
            "email already registered" in register_response.text
        ):
            login_response = self.client.post(
                "/api/v1/auth/login",
                json={"email": self.email, "password": self.password}
            )
            if login_response.status_code == 200:
                self.token = login_response.json().get("access_token")

    def _create_initial_project(self):
        """create initial project for testing"""
        if not self.token:
            return
        headers = {"Authorization": f"Bearer {self.token}"}
        project_data = {
            "name": f"Load Test Project {random.randint(1000, 9999)}",
            "description": "Initial project for load testing",
            "circuits": [],
            "activeCircuitId": ""
        }
        response = self.client.post("/api/v1/projects", json=project_data, headers=headers)
        if response.status_code == 201:
            self.project_ids.append(response.json()["id"])

    @task(5)
    def list_projects(self):
        """test list all projects"""
        if self.token:
            headers = {"Authorization": f"Bearer {self.token}"}
            response = self.client.get("/api/v1/projects", headers=headers)
            if response.status_code == 200:
                projects = response.json()
                # sync project_ids with actual projects to remove deleted ones
                if projects:
                    actual_ids = {p["id"] for p in projects}
                    self.project_ids = [pid for pid in self.project_ids if pid in actual_ids]
                    # add new projects if we have less than 10
                    if len(self.project_ids) < 10:
                        new_ids = [p["id"] for p in projects if p["id"] not in self.project_ids]
                        self.project_ids.extend(new_ids[:5])

    @task(3)
    def get_project(self):
        """test get single project"""
        if self.token and self.project_ids:
            headers = {"Authorization": f"Bearer {self.token}"}
            project_id = random.choice(self.project_ids)
            response = self.client.get(f"/api/v1/projects/{project_id}", headers=headers)
            # remove project ID if it doesn't exist
            if response.status_code == 404:
                self.project_ids.remove(project_id)

    @task(2)
    def create_project(self):
        """test create project"""
        if self.token:
            headers = {"Authorization": f"Bearer {self.token}"}
            project_data = {
                "name": f"Load Test Project {random.randint(10000, 99999)}",
                "description": "Generated by load test",
                "circuits": [],
                "activeCircuitId": ""
            }
            response = self.client.post("/api/v1/projects", json=project_data, headers=headers)
            if response.status_code == 201:
                project_id = response.json().get("id")
                if project_id and project_id not in self.project_ids:
                    self.project_ids.append(project_id)
            # silently ignore 500 errors (server-side issue, not test issue)

    @task(2)
    def update_project(self):
        """test update project"""
        if self.token and self.project_ids:
            headers = {"Authorization": f"Bearer {self.token}"}
            project_id = random.choice(self.project_ids)
            update_data = {
                "name": f"Updated Project {random.randint(1000, 9999)}",
                "description": "Updated description"
            }
            response = self.client.put(f"/api/v1/projects/{project_id}", json=update_data, headers=headers)
            # remove project ID if it doesn't exist
            if response.status_code == 404:
                if project_id in self.project_ids:
                    self.project_ids.remove(project_id)

    @task(1)
    def duplicate_project(self):
        """test duplicate project"""
        if self.token and self.project_ids:
            headers = {"Authorization": f"Bearer {self.token}"}
            project_id = random.choice(self.project_ids)
            response = self.client.post(f"/api/v1/projects/{project_id}/duplicate", headers=headers)
            if response.status_code == 201:
                new_project_id = response.json().get("id")
                if new_project_id and new_project_id not in self.project_ids:
                    self.project_ids.append(new_project_id)
            elif response.status_code == 404:
                # remove project ID if it doesn't exist
                if project_id in self.project_ids:
                    self.project_ids.remove(project_id)

    @task(1)
    def delete_project(self):
        """test delete project"""
        if self.token and len(self.project_ids) > 1:
            headers = {"Authorization": f"Bearer {self.token}"}
            project_id = self.project_ids.pop(0)
            response = self.client.delete(f"/api/v1/projects/{project_id}", headers=headers)
            # if delete failed, add it back
            if response.status_code == 404:
                if project_id not in self.project_ids:
                    self.project_ids.append(project_id)

