"""locust general load test - basic API endpoints"""
from locust import HttpUser, task, between
from locust.contrib.fasthttp import FastHttpUser
import random
from app.core.config import settings


class APIUser(HttpUser):
    """general API user behavior"""
    wait_time = between(1, 3)
    host = f"http://{'localhost' if settings.HOST == '0.0.0.0' else settings.HOST}:{settings.PORT}"

    def on_start(self):
        """login to get token"""
        self.token = None
        self.email = f"loadtest_{random.randint(100000, 999999)}@example.com"
        self.password = "TestPassword123!"
        self._register_and_login()

    def _register_and_login(self):
        """register user if needed and login"""
        register_data = {
            "email": self.email,
            "password": self.password,
            "first_name": "Load",
            "last_name": "Test"
        }
        register_response = self.client.post("/api/v1/auth/register", json=register_data)
        # only try login if registration succeeded (201) or user already exists (400)
        if register_response.status_code == 201 or (
            register_response.status_code == 400 and 
            "email already registered" in register_response.text
        ):
            login_response = self.client.post(
                "/api/v1/auth/login",
                json={"email": self.email, "password": self.password}
            )
            if login_response.status_code == 200:
                self.token = login_response.json().get("access_token")

    @task(5)
    def health_check(self):
        """health check endpoint"""
        self.client.get("/api/v1/health/")

    @task(3)
    def get_projects(self):
        """get user projects"""
        if self.token:
            headers = {"Authorization": f"Bearer {self.token}"}
            self.client.get("/api/v1/projects", headers=headers)

    @task(2)
    def get_me(self):
        """get current user info"""
        if self.token:
            headers = {"Authorization": f"Bearer {self.token}"}
            self.client.get("/api/v1/auth/me", headers=headers)

    @task(1)
    def create_project(self):
        """create a new project"""
        if self.token:
            headers = {"Authorization": f"Bearer {self.token}"}
            project_data = {
                "name": f"Load Test Project {random.randint(1000, 9999)}",
                "description": "Generated by load test",
                "circuits": [],
                "activeCircuitId": ""
            }
            self.client.post("/api/v1/projects", json=project_data, headers=headers)

    @task(1)
    def register_user(self):
        """register new user"""
        user_data = {
            "email": f"loadtest_{random.randint(10000, 99999)}@example.com",
            "password": "TestPassword123!",
            "first_name": "Load",
            "last_name": "Test"
        }
        self.client.post("/api/v1/auth/register", json=user_data)


class FastAPIUser(FastHttpUser):
    """faster HTTP user for higher throughput"""
    wait_time = between(0.5, 1.5)
    host = f"http://{'localhost' if settings.HOST == '0.0.0.0' else settings.HOST}:{settings.PORT}"

    def on_start(self):
        """setup: register and login to get token"""
        self.token = None
        self.email = f"fasttest_{random.randint(100000, 999999)}@example.com"
        self.password = "TestPassword123!"
        self._register_and_login()

    def _register_and_login(self):
        """register user if needed and login"""
        register_data = {
            "email": self.email,
            "password": self.password,
            "first_name": "Fast",
            "last_name": "Test"
        }
        register_response = self.client.post("/api/v1/auth/register", json=register_data)
        # only try login if registration succeeded (201) or user already exists (400)
        if register_response.status_code == 201 or (
            register_response.status_code == 400 and 
            "email already registered" in register_response.text
        ):
            login_response = self.client.post(
                "/api/v1/auth/login",
                json={"email": self.email, "password": self.password}
            )
            if login_response.status_code == 200:
                self.token = login_response.json().get("access_token")

    @task(10)
    def health_check(self):
        """health check - most frequent"""
        self.client.get("/api/v1/health/")

