"""comprehensive locust test - all user classes in one file"""
from locust import HttpUser, task, between
from locust.contrib.fasthttp import FastHttpUser
import random
from app.core.config import settings


class APIUser(HttpUser):
    """general API user behavior"""
    weight = 3
    wait_time = between(1, 3)
    host = f"http://{'localhost' if settings.HOST == '0.0.0.0' else settings.HOST}:{settings.PORT}"

    def on_start(self):
        """login to get token"""
        self.token = None
        self.email = f"loadtest_{random.randint(100000, 999999)}@example.com"
        self.password = "TestPassword123!"
        self._register_and_login()

    def _register_and_login(self):
        """register user if needed and login"""
        register_data = {
            "email": self.email,
            "password": self.password,
            "first_name": "Load",
            "last_name": "Test"
        }
        register_response = self.client.post("/api/v1/auth/register", json=register_data)
        # only try login if registration succeeded (201) or user already exists (400)
        if register_response.status_code == 201 or (
            register_response.status_code == 400 and 
            "email already registered" in register_response.text
        ):
            login_response = self.client.post(
                "/api/v1/auth/login",
                json={"email": self.email, "password": self.password}
            )
            if login_response.status_code == 200:
                self.token = login_response.json().get("access_token")

    @task(5)
    def health_check(self):
        """health check endpoint"""
        self.client.get("/api/v1/health/")

    @task(3)
    def get_projects(self):
        """get user projects"""
        if self.token:
            headers = {"Authorization": f"Bearer {self.token}"}
            self.client.get("/api/v1/projects", headers=headers)

    @task(2)
    def get_me(self):
        """get current user info"""
        if self.token:
            headers = {"Authorization": f"Bearer {self.token}"}
            self.client.get("/api/v1/auth/me", headers=headers)

    @task(1)
    def create_project(self):
        """create a new project"""
        if self.token:
            headers = {"Authorization": f"Bearer {self.token}"}
            project_data = {
                "name": f"Load Test Project {random.randint(1000, 9999)}",
                "description": "Generated by load test",
                "circuits": [],
                "activeCircuitId": ""
            }
            self.client.post("/api/v1/projects", json=project_data, headers=headers)

    @task(1)
    def register_user(self):
        """register new user"""
        user_data = {
            "email": f"loadtest_{random.randint(10000, 99999)}@example.com",
            "password": "TestPassword123!",
            "first_name": "Load",
            "last_name": "Test"
        }
        self.client.post("/api/v1/auth/register", json=user_data)


class FastAPIUser(FastHttpUser):
    """faster HTTP user for higher throughput"""
    weight = 1
    wait_time = between(0.5, 1.5)
    host = f"http://{'localhost' if settings.HOST == '0.0.0.0' else settings.HOST}:{settings.PORT}"

    def on_start(self):
        """setup: register and login to get token"""
        self.token = None
        self.email = f"fasttest_{random.randint(100000, 999999)}@example.com"
        self.password = "TestPassword123!"
        self._register_and_login()

    def _register_and_login(self):
        """register user if needed and login"""
        register_data = {
            "email": self.email,
            "password": self.password,
            "first_name": "Fast",
            "last_name": "Test"
        }
        register_response = self.client.post("/api/v1/auth/register", json=register_data)
        # only try login if registration succeeded (201) or user already exists (400)
        if register_response.status_code == 201 or (
            register_response.status_code == 400 and 
            "email already registered" in register_response.text
        ):
            login_response = self.client.post(
                "/api/v1/auth/login",
                json={"email": self.email, "password": self.password}
            )
            if login_response.status_code == 200:
                self.token = login_response.json().get("access_token")

    @task(10)
    def health_check(self):
        """health check - most frequent"""
        self.client.get("/api/v1/health/")


class AuthUser(HttpUser):
    """authentication endpoints performance"""
    weight = 2
    wait_time = between(1, 3)
    host = f"http://{'localhost' if settings.HOST == '0.0.0.0' else settings.HOST}:{settings.PORT}"

    def on_start(self):
        """setup: register and login to get token"""
        self.token = None
        self.refresh_token = None
        self.email = f"authtest_{random.randint(100000, 999999)}@example.com"
        self.password = "TestPassword123!"
        self._register_and_login()

    def _register_and_login(self):
        """register new user and login"""
        register_data = {
            "email": self.email,
            "password": self.password,
            "first_name": "Load",
            "last_name": "Test"
        }
        register_response = self.client.post("/api/v1/auth/register", json=register_data)
        # only try login if registration succeeded (201) or user already exists (400)
        if register_response.status_code == 201 or (
            register_response.status_code == 400 and 
            "email already registered" in register_response.text
        ):
            login_response = self.client.post(
                "/api/v1/auth/login",
                json={"email": self.email, "password": self.password}
            )
            if login_response.status_code == 200:
                data = login_response.json()
                self.token = data.get("access_token")
                self.refresh_token = data.get("refresh_token")

    @task(5)
    def login(self):
        """test login endpoint"""
        self.client.post(
            "/api/v1/auth/login",
            json={"email": self.email, "password": self.password}
        )

    @task(3)
    def get_me(self):
        """test get current user info"""
        if self.token:
            headers = {"Authorization": f"Bearer {self.token}"}
            self.client.get("/api/v1/auth/me", headers=headers)

    @task(2)
    def refresh_token(self):
        """test token refresh"""
        if self.refresh_token:
            self.client.post(
                "/api/v1/auth/refresh",
                json={"refresh_token": self.refresh_token}
            )

    @task(1)
    def register(self):
        """test user registration"""
        email = f"authtest_{random.randint(1000000, 9999999)}@example.com"
        self.client.post(
            "/api/v1/auth/register",
            json={
                "email": email,
                "password": "TestPassword123!",
                "first_name": "Load",
                "last_name": "Test"
            }
        )


class ProjectUser(HttpUser):
    """project CRUD operations performance"""
    weight = 2
    wait_time = between(1, 3)
    host = f"http://{'localhost' if settings.HOST == '0.0.0.0' else settings.HOST}:{settings.PORT}"

    def on_start(self):
        """setup: register, login and create initial project"""
        self.token = None
        self.project_ids = []
        self.email = f"projecttest_{random.randint(100000, 999999)}@example.com"
        self.password = "TestPassword123!"
        self._register_and_login()
        if self.token:
            self._create_initial_project()

    def _register_and_login(self):
        """register user if needed and login"""
        register_data = {
            "email": self.email,
            "password": self.password,
            "first_name": "Project",
            "last_name": "Test"
        }
        register_response = self.client.post("/api/v1/auth/register", json=register_data)
        # only try login if registration succeeded (201) or user already exists (400)
        if register_response.status_code == 201 or (
            register_response.status_code == 400 and 
            "email already registered" in register_response.text
        ):
            login_response = self.client.post(
                "/api/v1/auth/login",
                json={"email": self.email, "password": self.password}
            )
            if login_response.status_code == 200:
                self.token = login_response.json().get("access_token")

    def _create_initial_project(self):
        """create initial project for testing"""
        if not self.token:
            return
        headers = {"Authorization": f"Bearer {self.token}"}
        project_data = {
            "name": f"Load Test Project {random.randint(1000, 9999)}",
            "description": "Initial project for load testing",
            "circuits": [],
            "activeCircuitId": ""
        }
        response = self.client.post("/api/v1/projects", json=project_data, headers=headers)
        if response.status_code == 201:
            self.project_ids.append(response.json()["id"])

    @task(5)
    def list_projects(self):
        """test list all projects"""
        if self.token:
            headers = {"Authorization": f"Bearer {self.token}"}
            response = self.client.get("/api/v1/projects", headers=headers)
            if response.status_code == 200:
                projects = response.json()
                # sync project_ids with actual projects to remove deleted ones
                if projects:
                    actual_ids = {p["id"] for p in projects}
                    self.project_ids = [pid for pid in self.project_ids if pid in actual_ids]
                    # add new projects if we have less than 10
                    if len(self.project_ids) < 10:
                        new_ids = [p["id"] for p in projects if p["id"] not in self.project_ids]
                        self.project_ids.extend(new_ids[:5])

    @task(3)
    def get_project(self):
        """test get single project"""
        if self.token and self.project_ids:
            headers = {"Authorization": f"Bearer {self.token}"}
            project_id = random.choice(self.project_ids)
            response = self.client.get(f"/api/v1/projects/{project_id}", headers=headers)
            # remove project ID if it doesn't exist
            if response.status_code == 404:
                self.project_ids.remove(project_id)

    @task(2)
    def create_project(self):
        """test create project"""
        if self.token:
            headers = {"Authorization": f"Bearer {self.token}"}
            project_data = {
                "name": f"Load Test Project {random.randint(10000, 99999)}",
                "description": "Generated by load test",
                "circuits": [],
                "activeCircuitId": ""
            }
            response = self.client.post("/api/v1/projects", json=project_data, headers=headers)
            if response.status_code == 201:
                project_id = response.json().get("id")
                if project_id and project_id not in self.project_ids:
                    self.project_ids.append(project_id)
            # silently ignore 500 errors (server-side issue, not test issue)

    @task(2)
    def update_project(self):
        """test update project"""
        if self.token and self.project_ids:
            headers = {"Authorization": f"Bearer {self.token}"}
            project_id = random.choice(self.project_ids)
            update_data = {
                "name": f"Updated Project {random.randint(1000, 9999)}",
                "description": "Updated description"
            }
            response = self.client.put(f"/api/v1/projects/{project_id}", json=update_data, headers=headers)
            # remove project ID if it doesn't exist
            if response.status_code == 404:
                if project_id in self.project_ids:
                    self.project_ids.remove(project_id)

    @task(1)
    def duplicate_project(self):
        """test duplicate project"""
        if self.token and self.project_ids:
            headers = {"Authorization": f"Bearer {self.token}"}
            project_id = random.choice(self.project_ids)
            response = self.client.post(f"/api/v1/projects/{project_id}/duplicate", headers=headers)
            if response.status_code == 201:
                new_project_id = response.json().get("id")
                if new_project_id and new_project_id not in self.project_ids:
                    self.project_ids.append(new_project_id)
            elif response.status_code == 404:
                # remove project ID if it doesn't exist
                if project_id in self.project_ids:
                    self.project_ids.remove(project_id)

    @task(1)
    def delete_project(self):
        """test delete project"""
        if self.token and len(self.project_ids) > 1:
            headers = {"Authorization": f"Bearer {self.token}"}
            project_id = self.project_ids.pop(0)
            response = self.client.delete(f"/api/v1/projects/{project_id}", headers=headers)
            # if delete failed, add it back
            if response.status_code == 404:
                if project_id not in self.project_ids:
                    self.project_ids.append(project_id)


class CircuitUser(HttpUser):
    """circuit operations performance"""
    weight = 2
    wait_time = between(2, 5)
    host = f"http://{'localhost' if settings.HOST == '0.0.0.0' else settings.HOST}:{settings.PORT}"

    def on_start(self):
        """setup: register, login and create project with circuit"""
        self.token = None
        self.project_id = None
        self.circuit_id = None
        self.job_ids = []
        self.email = f"circuittest_{random.randint(100000, 999999)}@example.com"
        self.password = "TestPassword123!"
        self._register_and_login()
        if self.token:
            self._create_project_with_circuit()
            # retry if circuit creation failed
            if not self.circuit_id:
                self._create_project_with_circuit()

    def _register_and_login(self):
        """register user if needed and login"""
        register_data = {
            "email": self.email,
            "password": self.password,
            "first_name": "Circuit",
            "last_name": "Test"
        }
        register_response = self.client.post("/api/v1/auth/register", json=register_data)
        # only try login if registration succeeded (201) or user already exists (400)
        if register_response.status_code == 201 or (
            register_response.status_code == 400 and 
            "email already registered" in register_response.text
        ):
            login_response = self.client.post(
                "/api/v1/auth/login",
                json={"email": self.email, "password": self.password}
            )
            if login_response.status_code == 200:
                self.token = login_response.json().get("access_token")

    def _create_project_with_circuit(self):
        """create project with a circuit for testing"""
        if not self.token:
            return
        headers = {"Authorization": f"Bearer {self.token}"}
        circuit = {
            "id": f"circuit_{random.randint(1000, 9999)}",
            "name": "Test Circuit",
            "numQubits": 2,
            "gates": [
                {
                    "id": "gate1",
                    "depth": 0,
                    "gate": {"name": "H"},
                    "target_qubits": [0]
                },
                {
                    "id": "gate2",
                    "depth": 1,
                    "gate": {"name": "CNOT"},
                    "target_qubits": [0, 1]
                }
            ]
        }
        project_data = {
            "name": f"Circuit Test Project {random.randint(1000, 9999)}",
            "description": "Project for circuit testing",
            "circuits": [circuit],
            "activeCircuitId": circuit["id"]
        }
        response = self.client.post("/api/v1/projects", json=project_data, headers=headers)
        if response.status_code == 201:
            data = response.json()
            self.project_id = data["id"]
            if data.get("circuits"):
                self.circuit_id = data["circuits"][0]["id"]
        # if project creation failed, try to get circuit from existing projects
        elif response.status_code != 201 and not self.circuit_id:
            # try to get circuit from existing projects
            projects_response = self.client.get("/api/v1/projects", headers=headers)
            if projects_response.status_code == 200:
                projects = projects_response.json()
                for project in projects:
                    if project.get("circuits"):
                        self.project_id = project["id"]
                        self.circuit_id = project["circuits"][0]["id"]
                        break

    @task(5)
    def list_jobs(self):
        """test list jobs for circuit"""
        if self.token and self.circuit_id:
            headers = {"Authorization": f"Bearer {self.token}"}
            response = self.client.get(f"/api/v1/circuits/{self.circuit_id}/jobs", headers=headers)
            if response.status_code == 200:
                jobs = response.json().get("jobs", {})
                if jobs:
                    self.job_ids = list(jobs.keys())[:10]
            elif response.status_code == 404:
                # circuit might have been deleted, try to get a new one
                self.circuit_id = None
                if self.project_id:
                    headers = {"Authorization": f"Bearer {self.token}"}
                    project_response = self.client.get(f"/api/v1/projects/{self.project_id}", headers=headers)
                    if project_response.status_code == 200:
                        project = project_response.json()
                        if project.get("circuits"):
                            self.circuit_id = project["circuits"][0]["id"]

    @task(3)
    def get_job(self):
        """test get job status"""
        if self.token and self.circuit_id and self.job_ids:
            headers = {"Authorization": f"Bearer {self.token}"}
            job_id = random.choice(self.job_ids)
            response = self.client.get(f"/api/v1/circuits/{self.circuit_id}/jobs/{job_id}", headers=headers)
            if response.status_code == 404:
                # job doesn't exist, remove it from list
                if job_id in self.job_ids:
                    self.job_ids.remove(job_id)

    @task(2)
    def partition_circuit(self):
        """test partition circuit operation"""
        if self.token and self.circuit_id:
            headers = {"Authorization": f"Bearer {self.token}"}
            partition_data = {
                "num_qubits": 2,
                "placed_gates": [
                    {"gate": "H", "target": [0], "params": []},
                    {"gate": "CNOT", "target": [0, 1], "params": []}
                ],
                "measurements": [0, 1],
                "strategy": "kahn",
                "options": {}
            }
            response = self.client.post(
                f"/api/v1/circuits/{self.circuit_id}/partition",
                json=partition_data,
                headers=headers
            )
            if response.status_code == 200:
                job_id = response.json().get("job_id")
                if job_id:
                    self.job_ids.append(job_id)

    @task(1)
    def import_qasm(self):
        """test QASM import operation"""
        if self.token and self.circuit_id:
            headers = {"Authorization": f"Bearer {self.token}"}
            qasm_code = """
            OPENQASM 2.0;
            include "qelib1.inc";
            qreg q[2];
            h q[0];
            cx q[0], q[1];
            measure q[0] -> c[0];
            measure q[1] -> c[1];
            """
            response = self.client.post(
                f"/api/v1/circuits/{self.circuit_id}/import-qasm",
                json={"qasm_code": qasm_code},
                headers=headers
            )
            if response.status_code == 200:
                job_id = response.json().get("job_id")
                if job_id:
                    self.job_ids.append(job_id)

