[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "qubitkit"
version = "0.1.3"
description = "Quantum Unitary Benchmarking and Interactive Toolkit"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "Muhammad Al Farizi"}
]
requires-python = ">=3.8"
dependencies = [
    "qiskit",
    "numpy>=1.20.0"
]

[project.optional-dependencies]
dev = [
    "build",
    "twine",
    "pytest"
]
viz = [
    "matplotlib>=3.5.0",
    "plotly>=5.0.0"
]

[tool.setuptools.packages.find]